name: "build"
on: [push]

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
    - uses: "actions/checkout@v2"
    - run: |
        sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi
    - run: "make"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Development build"
        files: |
          arm9linuxfw.bin
